packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  canvas: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
  vue-demi: true

overrides:
  linkify-it: 5.0.1
