packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - '@google/genai'
  - '@parcel/watcher'
  - canvas
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - vue-demi

overrides:
  linkify-it: 5.0.1
